name: emergency
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_onboarding_slider: ^1.0.11
  lottie: ^3.1.2
  flutter_login: ^5.0.0
  firebase_auth: ^4.16.0
  shared_preferences: ^2.3.2
  flutter_native_splash: ^2.4.1
  cached_network_image: ^3.4.1
  google_maps_flutter: ^2.3.0
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  supabase_flutter: ^2.3.3
  geocoding: ^3.0.0
  mailer: ^6.1.2
  google_sign_in: ^6.2.1
  multi_select_flutter: ^4.1.3

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/splash.png"
  

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.png
  android: true
  ios: true
  android_12:
    color: "#FFFFFF"
    image: assets/splash.png

flutter:
  uses-material-design: true
  assets:
    - assets/
