// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK3WE7exg1X03nMvOXzZD6TxQ7oACTiI8',
    appId: '1:861966612370:web:440d2504cfab29e4a0f34b',
    messagingSenderId: '861966612370',
    projectId: 'emergency-f1897',
    authDomain: 'emergency-f1897.firebaseapp.com',
    storageBucket: 'emergency-f1897.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtFfhmh5abhkQGEaWW-kJhW2HEkszQqNw',
    appId: '1:861966612370:android:b38051e58a0f1fb5a0f34b',
    messagingSenderId: '861966612370',
    projectId: 'emergency-f1897',
    storageBucket: 'emergency-f1897.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCih4RrLaUUTCLbDwXipB5S1_e5zk5I-P0',
    appId: '1:861966612370:ios:ed423bf16f8e60caa0f34b',
    messagingSenderId: '861966612370',
    projectId: 'emergency-f1897',
    storageBucket: 'emergency-f1897.appspot.com',
    iosBundleId: 'com.example.emergency',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCih4RrLaUUTCLbDwXipB5S1_e5zk5I-P0',
    appId: '1:861966612370:ios:ed423bf16f8e60caa0f34b',
    messagingSenderId: '861966612370',
    projectId: 'emergency-f1897',
    storageBucket: 'emergency-f1897.appspot.com',
    iosBundleId: 'com.example.emergency',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK3WE7exg1X03nMvOXzZD6TxQ7oACTiI8',
    appId: '1:861966612370:web:22f6b39f7d34063fa0f34b',
    messagingSenderId: '861966612370',
    projectId: 'emergency-f1897',
    authDomain: 'emergency-f1897.firebaseapp.com',
    storageBucket: 'emergency-f1897.appspot.com',
  );
}
